name: Submit URLs to IndexNow

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find updated URLs and submit to IndexNow
        run: |
          BASE_URL="https://mdhdj.github.io/danske-souvenirs"
          KEY="102134adcd644d5caf17c62f35c4ba25"
          KEY_URL="$BASE_URL/$KEY.txt"

          # اجمع كل صفحات HTML
          URLS=$(find . -name "*.html" | sed 's|^\./||' | sed "s|^|$BASE_URL/|")

          # أنشئ JSON
          JSON=$(jq -n \
            --arg key "$KEY" \
            --arg host "mdhdj.github.io" \
            --arg keyLocation "$KEY_URL" \
            --argjson urlList "$(echo \"$URLS\" | jq -R -s -c 'split("\n")[:-1]')" \
            '{host: $host, key: $key, keyLocation: $keyLocation, urlList: $urlList}')

          echo "$JSON" > payload.json

          # أرسل إلى IndexNow
          curl -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d @payload.json
